# Generated by Django 5.2.1 on 2025-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotaskmodel',
            options={'ordering': ['creationTime', 'isCompleted']},
        ),
        migrations.AlterField(
            model_name='todotaskmodel',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todotaskmodel',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
