# Generated by Django 5.2.1 on 2025-06-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_todotaskmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotaskmodel',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='todotaskmodel',
            name='isCompleted',
        ),
    ]
