# Generated by Django 5.2.1 on 2025-06-01 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_todotaskmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotaskmodel',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todotaskmodel',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
